### ISSUE TITLE
Modify documentation to remove reference to Win SCP as a file tranfer method.

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/docs#10]
Two matters have been raised in the J! Forum about the self-delete feature in the current FPA.  They are 

1. https://forum.joomla.org/viewtopic.php?f=806&t=982234
2. https://forum.joomla.org/viewtopic.php?f=806&t=983903

The [documentation ](https://forumpostassistant.github.io/docs/admin-guide/) states:

>  You can use your operating systems native FTP command-line tools or any of the following File Transfer (FTP) or Secure Copy (SCP) applications will do the job: Transmit, WinSCP, CyberDuck, FileZilla

It may not be true to say that "any" of those FTP or SCP applications will work if the transfer method does not update the file modified date on the target location (as discussed at https://forum.joomla.org/viewtopic.php?f=806&t=982234#p3615105) and I would suggest writing a caveat in the documentation about using applications like _Win SCP_.

**Comment by RussW** [comment]
"Secure Copy" is an older protocol but is still used regularly by experienced Systems Administrators, preserving the timestamp is the default method as it is considered to be an exact "*copy*" of a file, not an upload or transfer. So whilst this isn't technically a bug within FPA, for an in-experienced user of SCP it will be confusing and they are likely to observe issues caused by the modified timestamp not being updated to the current copy/transfer time, of which will cause auto-delete function be immediately (or unexpectedly) invoked as the modified date is used to calculate the auto-delete period. 
 
**Documentation updated** as requested to include a new "Tip/Notice" on both Quick Start Guide and Administrator pages regarding unchecking/disable "Preserve Timestamp" in the session options *(as specified in the WinSCP documentation)* to avoid auto-delete issues.

[edit] *as an aside and for future reference, the same issue would occur if the user uploads/transfers the FPA as part of a "synchronised" file transfer through (s)FTP or SCP as the modified date would be preserved in order to control what needs sync'ing and when.*

**Comment by sozzled** [comment]
Thanks.  This looks good to me.
